In [1]:
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from tools.io import load_probe, load_units_metadata

data_path = Path("/Volumes/fsmresfiles/Basic_Sciences/Phys/SenzaiLab/Elissa_Belluccini/Kilosort/Mouse10_20260210_795to2220")
kspath = data_path / 'ProbeA' / 'kilosort'
kspath2 = Path('/Volumes/fsmresfiles/Basic_Sciences/Phys/SenzaiLab/pipeline_output/aa005/ProbeA/kilosort')
json_path = data_path / 'ProbeA' / 'concat' / 'probe.json'

In [7]:
load_probe(kspath)

         x   depth  shank_ids  depth_rank
202    0.0   795.0          0           0
205   32.0   810.0          0           1
206    0.0   825.0          0           2
209   32.0   840.0          0           3
210    0.0   855.0          0           4
..     ...     ...        ...         ...
193  782.0  2160.0          3          91
194  750.0  2175.0          3          92
197  782.0  2190.0          3          93
198  750.0  2205.0          3          94
201  782.0  2220.0          3          95

[384 rows x 4 columns]

In [8]:
load_probe(kspath2)

         x   depth  shank_ids  depth_rank
0      0.0     0.0          0           0
3     32.0    15.0          0           1
4      0.0    30.0          0           2
7     32.0    45.0          0           3
8      0.0    60.0          0           4
..     ...     ...        ...         ...
183  782.0  1365.0          3          91
184  750.0  1380.0          3          92
187  782.0  1395.0          3          93
188  750.0  1410.0          3          94
191  782.0  1425.0          3          95

[384 rows x 4 columns]

In [9]:
load_units_metadata(kspath)

,cluster_id,Amplitude,ContamPct,KSLabel,amp,ch,depth,fr,group,n_spikes,shank_ids,depth_rank
18,18,21.7,16.0,good,1145.087158,230,1005.0,1.249198,good,45461,0.0,0
23,23,24.2,0.0,good,1156.366943,237,1050.0,0.589138,good,21440,0.0,1
26,26,10.4,16.6,good,637.222900,238,1065.0,2.639003,good,96039,0.0,2
29,29,23.9,0.0,good,1542.479858,238,1065.0,0.697101,good,25369,0.0,3
32,32,16.7,17.0,good,879.740479,238,1065.0,10.165872,good,369958,0.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...
992,1002,26.8,3.6,good,2023.548828,108,1890.0,1.511699,good,55014,3.0,50
994,1004,18.8,17.6,good,1213.608765,108,1890.0,1.929619,good,70223,3.0,51
996,1006,22.2,11.7,good,1466.539185,112,1920.0,1.710836,good,62261,3.0,52
1009,1019,17.6,12.0,good,1087.438232,116,1950.0,1.833170,good,66713,3.0,53
1027,1037,16.3,7.1,good,1023.959106,136,2100.0,8.100701,good,294802,3.0,54

In [10]:
load_units_metadata(kspath2)

                     x       depth  nearest_channel  shank_ids  depth_rank
cluster_id
3            21.112055   31.861803                7        0.0           0
6             9.921768   50.603306                8        0.0           1
11           15.985299   57.702000                8        0.0           2
7            19.379601   62.171154               11        0.0           3
13            9.284454   65.403053                8        0.0           4
...                ...         ...              ...        ...         ...
494         762.005310  953.099060               80        3.0          17
497         762.853882  953.503967               80        3.0          18
501         761.808655  993.729553               84        3.0          19
500         762.192383  994.937195               84        3.0          20
499         762.666870  995.047668               84        3.0          21

[136 rows x 5 columns]